#!/bin/bash
_golded_lang=ru_RU.UTF-8
_locale_check=utf8
_locale_message="${_golded_lang} UTF-8"
_gedlnx=$(which gedlnx)

if [ ! -x ${_gedlnx} ]; then
    echo "gedlnx is not avaiable/executable, sorry"
    exit 1
fi

_has_locale=$(locale -a | grep ${_locale_check})
if [ -z ${_has_locale} ]; then
    echo -n "Checking system locale presence ${_locale_check}: "
    echo "Not avaiable!"
    echo "Add ${_locale_message} to /etc/locale.gen and run"
    echo "sudo locale-gen"
    exit 1
fi

if [ "$LANG" = "${_golded_lang}" ]; then
    exec "${_gedlnx}" "$@"
else
    LANG=${_golded_lang} exec "${_gedlnx}" "$@"
fi
